### ISSUE TITLE
Reconsider Styling Setup

### ISSUE THREAD

**Issue by zainfathoni** [devpendent/website#23]
I tried to use `react-bulma-components` in building the home page (you can check it out in my `content/home` branch), but I personally felt that it's not intuitive enough, because we still have to touch `.sass` files.

Besides, when I tried to follow [this configuration](https://github.com/couds/react-bulma-components#gatsby), it didn't work at all.
I think the integration effort doesn't worth it.

Based on my experience with Ant Design, I think it's pretty convenient to work with. Therefore I'm reconsidering to replace it with Ant Design now.

What do you think about it @ri7nz?

**Comment by ri7nz** [comment]
If we want to replace with Antd, I agree. In my based experience with antd ,too.

**Comment by zainfathoni** [comment]
Okay, then.
Let's do it. 😂

**Comment by zainfathoni** [comment]
Okay, then.
Let's do it!
